data:
  loaders:
    batch_size: 4
    num_workers: 4
  
  files:
    base: /home/mila/t/tengmeli/Duckietown_project_fall2020/DARLA/
    train: train.txt
    val: val.txt

  max_samples: -1

  transforms:
    - name: hflip
      ignore: false
      p: 0.5
    - name: resize
      ignore: false
      new_size: 640
    - name: crop
      ignore: false
      height: 600
      width: 600
    - name: colorjitter
      ignore: false
      brightness: 0
      contrast: 0
      saturation: 0
      hue: 0
      
    - name: resize 
      ignore: false
      new_size: 640
